
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend
    depends_on:
      - php
      - mysql

  php:
    build: ./php
    networks:
      - backend
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  db_data:
